import { AssetManifest } from './AssetLoader';

/**
 * Game Asset Manifest
 * This file defines all game assets loaded through the art pipeline
 */
export const GAME_ASSETS: AssetManifest = {
  atlases: [
    // Character atlases (when generated by TexturePacker)
    // {
    //   key: 'characters_atlas',
    //   imagePath: '/content/art/characters/atlas/characters_atlas.png',
    //   dataPath: '/content/art/characters/atlas/characters_atlas.json'
    // }
  ],
  
  sprites: [
    // Character sprites
    {
      key: 'hero',
      path: '/content/art/characters/export/hero.png',
      frameWidth: 32,
      frameHeight: 32
    },
    
    // Environment tiles
    {
      key: 'environment',
      path: '/content/art/tiles/export/environment.png',
      frameWidth: 32,
      frameHeight: 32
    },
    
    // Mob sprites
    {
      key: 'basic_mobs',
      path: '/content/art/mobs/export/basic_mobs.png',
      frameWidth: 32,
      frameHeight: 32
    },
    
    // Item icons
    {
      key: 'basic_items',
      path: '/content/art/items/export/basic_items.png',
      frameWidth: 32,
      frameHeight: 32
    },
    
    // UI elements
    {
      key: 'ui_elements',
      path: '/content/art/ui/export/ui_elements.png'
    },
    
    // VFX sprites
    {
      key: 'effects',
      path: '/content/art/vfx/export/effects.png',
      frameWidth: 32,
      frameHeight: 32
    }
  ],
  
  animations: [
    // Hero character animations
    {
      key: 'hero_idle_down',
      spriteKey: 'hero',
      frames: [0],
      frameRate: 1,
      repeat: 0
    },
    {
      key: 'hero_idle_left',
      spriteKey: 'hero',
      frames: [4],
      frameRate: 1,
      repeat: 0
    },
    {
      key: 'hero_idle_right',
      spriteKey: 'hero',
      frames: [8],
      frameRate: 1,
      repeat: 0
    },
    {
      key: 'hero_idle_up',
      spriteKey: 'hero',
      frames: [12],
      frameRate: 1,
      repeat: 0
    },
    {
      key: 'hero_walk_down',
      spriteKey: 'hero',
      frames: { start: 0, end: 3 },
      frameRate: 8
    },
    {
      key: 'hero_walk_left',
      spriteKey: 'hero',
      frames: { start: 4, end: 7 },
      frameRate: 8
    },
    {
      key: 'hero_walk_right',
      spriteKey: 'hero',
      frames: { start: 8, end: 11 },
      frameRate: 8
    },
    {
      key: 'hero_walk_up',
      spriteKey: 'hero',
      frames: { start: 12, end: 15 },
      frameRate: 8
    },
    
    // VFX animations
    {
      key: 'vfx_slash',
      spriteKey: 'effects',
      frames: [0],
      frameRate: 12,
      repeat: 0
    },
    {
      key: 'vfx_spark',
      spriteKey: 'effects',
      frames: [1],
      frameRate: 15,
      repeat: 0
    },
    {
      key: 'vfx_impact',
      spriteKey: 'effects',
      frames: [2],
      frameRate: 20,
      repeat: 0
    },
    {
      key: 'vfx_heal',
      spriteKey: 'effects',
      frames: [3],
      frameRate: 8,
      repeat: 2
    },
    {
      key: 'vfx_fireball',
      spriteKey: 'effects',
      frames: [4],
      frameRate: 12,
      repeat: 0
    },
    {
      key: 'vfx_ice',
      spriteKey: 'effects',
      frames: [5],
      frameRate: 10,
      repeat: 0
    },
    {
      key: 'vfx_lightning',
      spriteKey: 'effects',
      frames: [6],
      frameRate: 15,
      repeat: 0
    },
    {
      key: 'vfx_poison',
      spriteKey: 'effects',
      frames: [7],
      frameRate: 6,
      repeat: -1
    }
  ]
};

/**
 * Tile mapping for environment tileset
 */
export const TILE_INDICES = {
  GRASS: 0,
  GRASS_FLOWER: 1,
  GRASS_ROCK: 2,
  GRASS_EDGE: 3,
  DIRT: 4,
  DIRT_PATH: 5,
  DIRT_EDGE: 6,
  DIRT_CORNER: 7,
  STONE: 8,
  STONE_WALL: 9,
  STONE_BRICK: 10,
  STONE_CRACKED: 11,
  WATER: 12,
  WATER_EDGE: 13,
  WATER_CORNER: 14,
  WATER_DEEP: 15
};

/**
 * Mob sprite indices
 */
export const MOB_INDICES = {
  SLIME: 0,
  SPIDER: 1,
  SKELETON: 2
};

/**
 * Item sprite indices
 */
export const ITEM_INDICES = {
  SWORD: 0,
  POTION: 1,
  SHIELD: 2,
  COIN: 3
};

/**
 * VFX sprite indices
 */
export const VFX_INDICES = {
  SLASH: 0,
  SPARK: 1,
  IMPACT: 2,
  HEAL: 3,
  FIREBALL: 4,
  ICE: 5,
  LIGHTNING: 6,
  POISON: 7
};